### ISSUE TITLE
Policies: Create Policy through wizard must support non-pcap policies 

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1089]
When sflow is choosed as policy tap, on current ORB the UI not allowed the user to proceed with the policy creation process and not adjust the form considering the tap.

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/110dca10-d96d-4a85-bdd7-8166298c4408)

The expected behavior is that the UI adjust the dynamic form for config. 

Sflow requires a bind and port field on configs and only allows net handler. 

Json:

```
        "input": {
            "input_type": "sflow",
            "tap": "default_sflow",
            "config": {
                "port": 6343,
                "bind": "192.168.0.1"
            }
```

Yaml:

``` 
   taps:
      default_sflow:
         input_type: sflow
         config:
            port: 6343
            bind: "192.168.0.1"
```
