### ISSUE TITLE
Tests: validate example of advanced policies in yaml and json to insert on documentation

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1710]
With the documentation of possible inputs, handlers, settings and filters, make and test some advanced policies that can be placed as a basis for the user in the documentation..

- Validate inserting on orb UI [ ]
- Validate inserting trhough API [ ]
- Validate applying on pktvisor [ ]

**Comment by manrodrigues** [comment]
input:
  tap: tap_name
  input_type: type_of_input
  filter:
    bpf: ...
  config:
    ...
handlers:
  config:
    deep_sample_rate: 100
    num_periods: 5
    topn_count: 10
  modules:
    tap_name:
      type: ...
      config: ...
      filter: ...
      metric_groups:
        enable:
          - ...
        disable:
          - ...
kind: collection

**Comment by manrodrigues** [comment]
```
input:
  tap: tap_name
  input_type: type_of_input
  filter:
    bpf: ...
  config:
    ...
handlers:
  config:
    deep_sample_rate: 100
    num_periods: 5
    topn_count: 10
  modules:
    tap_name:
      type: ...
      config: ...
      filter: ...
      metric_groups:
        enable:
          - ...
        disable:
          - ...
kind: collection
    
```

**Comment by manrodrigues** [comment]
still failing: 

```
version: "1.0"

visor:
    policies:
        policy1:
            input:
                tap: default
                input_type: pcap
                filter:
                    bpf: udp port 53
                config:
                    pcap_file: /home/arodrigues/Documents/pktvisor/src/tests/fixtures/
            kind: collection
            handlers:
                modules:
                    default:
                        type: pcap
```
