### ISSUE TITLE
OpenTelemetry MVP POCs

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1749]
New TODOs

- [ ] Generate YAML for config map from Sink Config - @mclcavalcante 
- [ ] Create OTel-Collector which receive multiple YAML configurations and trigger multiple pipelines with go-routines  @lpegoraro 
- [ ] Deploy OTel-Collector MVP in K8s Kind @etaques 
- [ ] Develop mechanism to build and update YAML configuration on change of Sinks information and update OTel-Collector MVP deployed service
- [ ] Deploy OTel-Collector in K8s Staging
- [ ] Deploy OTel-Collector in K8s Prod

**Comment by lpegoraro** [comment]
Sinks service will generate a new Topic in Redis, containing a configuration YAML, 
And with each change Sinks service creates/updates a new entry in the Topic of Running Collectors, with the parsed YAML:

**Comment by lpegoraro** [comment]
The YAML  will look like this

config-yaml-{{sink-id}}
```yaml
receivers:
    otlp:
    protocols: # TBD
       grpc:
          auth: 
             authenticator: basicauth/sinker

extensions:
  health_check: {}
  basicauth/exporter:
    client_auth: 
      username: {sinker-grpc}
      password: {sinker-grpc}
   # for bearer token
   bearertokenauth:
     token: {sink-bearer-token}
   # for basic auth
   basicauth/exporter:
    client_auth: 
      username: {sink-username}
      password: {sink-password}

processors:
    
exporters:
  prometheusremotewrite:
    endpoint: "{sink-endpoint}"
```
