### ISSUE TITLE
Short form Orb Agent startup

### ISSUE THREAD

**Issue by rboucher-ns1** [ns1labs/orb#1897]
When starting an Orb agent as a docker container, it should support a command "short form" to get going quickly.

Basic short form command:
```bash
docker run -d --net=host \
-e ORB_CLOUD_MQTT_ID=<AGENT_ID> \
-e ORB_CLOUD_MQTT_CHANNEL_ID=<CHANNEL_ID> \
-e ORB_CLOUD_MQTT_KEY=<AGENT_KEY> \ 
ns1labs/orb-agent
```

Short form command with a configuration file:
```bash
docker run -d --net=host \
-e ORB_CLOUD_MQTT_ID=<AGENT_ID> \
-e ORB_CLOUD_MQTT_CHANNEL_ID=<CHANNEL_ID> \
-e ORB_CLOUD_MQTT_KEY=<AGENT_KEY> \ 
-v ${PWD}/agent.yaml:/usr/local/orb/agent.yaml 
ns1labs/orb-agent
```

In both cases, a default `agent.yaml` should exist in the Orb agent to provide all necessary values that aren't provided explicitly by the user (including the "basic short form" case where none of these values are provided by the user). In the case where a configuration file is passed ("short form with a config file"), only the values defined in this configuration file will replace the equivalent values in the default configuration file.  Here is an example of what this `agent.yaml` _could_ look like:

```yaml
version: "1.0"

visor:
   taps:
      default_pcap:
         input_type: pcap
         config:
            iface: "auto"

orb:
   cloud:
      config:
         auto_provision: true
      api:
         address: https://orb.live
      mqtt:
         address: tls://orb.live:8883
   backends:
      pktvisor:
        binary: "/usr/local/sbin/pktvisord"
        config_file: "/usr/local/orb/default_agent.yaml"
```

**Comment by manrodrigues** [comment]
@etaques just remembering that we need to check why the path inside .yaml is not being considered

**Comment by manrodrigues** [comment]
I'll try to help with some scenarios that I already tested and then we can think together if there is some other important things to validate before consider it a valid fix:


1) Mounting the config file directly in the default path:

```
docker run -d --net=host \
-e ORB_CLOUD_MQTT_ID=9af04a0a-47b9-473f-a92e-e5acb88d67ea \
-e ORB_CLOUD_MQTT_CHANNEL_ID=27d34d8b-5c6a-4ed3-8ece-ab446231976f \
-e ORB_CLOUD_MQTT_KEY=0e46d8b9-f08e-484b-bb21-5a68c45a0c35 \
-v ${PWD}/orb-agent.yaml:/etc/orb/agent.yaml \
ns1labs/orb-agent:0.21.0-f8977f7c
```
orb-agent.yaml:

```
orb:
  backends:
    pktvisor:
      api_port: "10857"
      binary: /usr/local/sbin/pktvisord
      config_file: /etc/orb/agent.yaml
  cloud:
    api:
      address: https://stg.orb.live
    config:
      auto_provision: false
    mqtt:
      address: tls://stg.orb.live:8883
  tags:
      test: policy
  tls:
    verify: true
version: '1.0'
visor:
  taps:
    default_pcap:
      config:
        iface: wlo1
      input_type: pcap
```
Agent logs:

[_relaxed_snyder_logs.txt](https://github.com/ns1labs/orb/files/9974615/_relaxed_snyder_logs.txt)


2) Mounting the config file directly in the default path and specifying the file via -c :

```
docker run -d --net=host \
-e ORB_CLOUD_MQTT_ID=9af04a0a-47b9-473f-a92e-e5acb88d67ea \
-e ORB_CLOUD_MQTT_CHANNEL_ID=27d34d8b-5c6a-4ed3-8ece-ab446231976f \
-e ORB_CLOUD_MQTT_KEY=0e46d8b9-f08e-484b-bb21-5a68c45a0c35 \
-v ${PWD}/orb-agent.yaml:/etc/orb/agent.yaml \
ns1labs/orb-agent:0.21.0-f8977f7c run -c /etc/orb/agent.yaml
```

Agent Logs:

[_stupefied_hopper_logs.txt](https://github.com/ns1labs/orb/files/9974640/_stupefied_hopper_logs.txt)


3) Mounting the config file directly in other path:

```
docker run -d --net=host \
-e ORB_CLOUD_MQTT_ID=9af04a0a-47b9-473f-a92e-e5acb88d67ea \
-e ORB_CLOUD_MQTT_CHANNEL_ID=27d34d8b-5c6a-4ed3-8ece-ab446231976f \
-e ORB_CLOUD_MQTT_KEY=0e46d8b9-f08e-484b-bb21-5a68c45a0c35 \
-v ${PWD}/orb-agent.yaml:/usr/local/orb/agent.yaml \
ns1labs/orb-agent:0.21.0-f8977f7c
```
orb-agent.yaml:

```
orb:
  backends:
    pktvisor:
      api_port: "10857"
      binary: /usr/local/sbin/pktvisord
      config_file: /usr/local/orb/agent.yaml
  cloud:
    api:
      address: https://stg.orb.live
    config:
      auto_provision: false
    mqtt:
      address: tls://stg.orb.live:8883
  tags:
      test: policy
  tls:
    verify: true
version: '1.0'
visor:
  taps:
    default_pcap:
      config:
        iface: wlo1
      input_type: pcap
```

Agents fails (as expected) because tried to use the default config.

Agent Logs:

[_upbeat_tu_logs.txt](https://github.com/ns1labs/orb/files/9974667/_upbeat_tu_logs.txt)


4) Mounting the config file directly in other path and specifying the file via -c:

```
docker run -d --net=host \
-e ORB_CLOUD_MQTT_ID=9af04a0a-47b9-473f-a92e-e5acb88d67ea \
-e ORB_CLOUD_MQTT_CHANNEL_ID=27d34d8b-5c6a-4ed3-8ece-ab446231976f \
-e ORB_CLOUD_MQTT_KEY=0e46d8b9-f08e-484b-bb21-5a68c45a0c35 \
-v ${PWD}/orb-agent.yaml:/usr/local/orb/agent.yaml \
ns1labs/orb-agent:0.21.0-f8977f7c run -c /usr/local/orb/agent.yaml
```

Agent Logs:

[_sleepy_joliot_logs.txt](https://github.com/ns1labs/orb/files/9974695/_sleepy_joliot_logs.txt)

5) Mounting a directory:

```
docker run -d --net=host  -v ${PWD}/orb:/orb ns1labs/orb-agent:0.21.0-f8977f7c run -c /orb/orb-agent.yaml
```

orb-agent.yaml:

```
orb:
  backends:
    pktvisor:
      api_port: "10857"
      binary: /usr/local/sbin/pktvisord
      config_file: /orb/orb-agent.yaml
  cloud:
    api:
      address: https://stg.orb.live
    config:
      auto_provision: false
    mqtt:
      address: tls://stg.orb.live:8883
      id: "9af04a0a-47b9-473f-a92e-e5acb88d67ea"
      key: "0e46d8b9-f08e-484b-bb21-5a68c45a0c35"
      channel_id: "27d34d8b-5c6a-4ed3-8ece-ab446231976f"
  tags:
      test: policy
  tls:
    verify: true
version: '1.0'
visor:
  taps:
    default_pcap:
      config:
        iface: wlo1
      input_type: pcap
```

[_cranky_cartwright_logs.txt](https://github.com/ns1labs/orb/files/9974740/_cranky_cartwright_logs.txt)
