### ISSUE TITLE
pktvisor should use default values if nothing is specified in Orb agent configuration file

### ISSUE THREAD

**Issue by rboucher-ns1** [ns1labs/orb#2039]
This issue targets the following two pktvisor settings that can be specified in the Orb agent configuration file:
- `binary`
- `config_file`

If either of these values is _not_ specified, the following default values should be given:
```yaml
orb:
  backends:
    pktvisor:
      binary: /usr/local/sbin/pktvisord
      config_file: /opt/orb/agent.yaml
```

This should allow a pktvisor backend to be defined _without_ requiring these settings to be provided by the user explicitly.
