### ISSUE TITLE
Pktvisor: when a policy is removed and another one is created with same name pktvisor returns conflict error and end execution by segmentation fault

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#733]
Steps to reproduce:

1 - docker pull ns1labs/pktvisor
2 - curl -L http://pktvisor.com/download -o pktvisor-x86_64.AppImage
3 - chmod +x pktvisor-x86_64.AppImage
4 - sudo ./pktvisor-x86_64.AppImage pktvisord -v --admin-api `<network-interface>` (replace `<network-interface>` with your own interface)
5 - (replace `<network-interface>` with your own interface)
```
curl --location --request POST 'localhost:10853/api/v1/policies' \
--header 'Content-Type: application/x-yaml' \
--data-raw 'version: "1.0"
visor:
  taps:
    default:
      input_type: pcap
      config:
        iface: "<network-interface>"
        host_spec: ""
  policies:
    default_1:
      kind: collection
      input:
        tap: default
        input_type: pcap
        config:
          bpf: ""
      handlers:
        window_config:
          num_periods: 5
          deep_sample_rate: 100
        modules:
          net:
            type: net
          dhcp:
            type: dhcp
          dns:
            type: dns
          pcap_stats:
            type: pcap
'
```

<br>

6 - (replace `<network-interface>` with your own interface)

```
curl --location --request DELETE 'localhost:10853/api/v1/policies' \
--header 'Content-Type: application/x-yaml' \
--data-raw 'version: "1.0"
visor:
  taps:
    default:
      input_type: pcap
      config:
        iface: "<network-interface>"
        host_spec: ""
  policies:
    default_1:
      kind: collection
      input:
        tap: default
        input_type: pcap
        config:
          bpf: ""
      handlers:
        window_config:
          num_periods: 5
          deep_sample_rate: 100
        modules:
          net:
            type: net
          dhcp:
            type: dhcp
          dns:
            type: dns
          pcap_stats:
            type: pcap
'
```
7 - repeat step 5 (POST REQUEST)

Current result:

![image](https://user-images.githubusercontent.com/78241475/148558023-063bd13e-e296-4da5-bd06-24f04f1215d8.png)
