### ISSUE TITLE
FIx Agent Policy Case

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#760]
Agent Config 
```
    version: "1.0"
    
    # this section is used by pktvisor
    # see https://github.com/ns1labs/pktvisor/blob/develop/RFCs/2021-04-16-75-taps.md
    visor:
    #   config:
    #      geo_city: "/geo/GeoIP2-City.mmdb"
    #      geo_asn: "/geo/GeoIP2-ISP.mmdb"
       taps:
          dnstap:
             input_type: dnstap
             config:
                tcp: "0.0.0.0:535
    
    # this section is used orb-agent
    # most sections and keys are optional
    orb:
       backends:
          pktvisor:
             binary: "/usr/local/sbin/pktvisord"
             config_file: "/orb/orb-agent.yaml"
       cloud:
          api:
             address: https://orb.live
          mqtt:
             address: tls://orb.live:8883
             id: "something"
             key: "something"
             channel_id: "something"
```

endpoint command 
```
          command:
            - /usr/local/bin/orb-agent
            - run
            - -c
            - /orb/orb-agent.yaml
```

policy config 
```
curl --location --request POST 'https://orb.live:/api/v1/policies/agent' \
--header 'Content-Type: application/json' \
--header 'Authorization: JWT' \
--data-raw '{
    "name": "dnstap-all",
    "tags": {},
    "backend": "pktvisor",
    "policy": {
        "handlers": {
            "modules": {
                "handler_dns_1": {
                    "type": "dns"
                },
                "handler_net_1": {
                    "type": "net"
                }
            }
        },
        "input": {
            "input_type": "dnstap",
            "tap": "dnstap"
        },
        "kind": "collection"
    }
}'
```

**Comment by gpazuch** [comment]
```
version: "1.0"

# this section is used by pktvisor
# see https://github.com/ns1labs/pktvisor/blob/develop/RFCs/2021-04-16-75-taps.md
visor:
  #   config:
  #      geo_city: "/geo/GeoIP2-City.mmdb"
  #      geo_asn: "/geo/GeoIP2-ISP.mmdb"
  taps:
    dnstap:
      input_type: dnstap
      config:
        tcp: "0.0.0.0:5353"

orb:
  tls:
    verify: false
  backends:
    pktvisor:
      binary: "/usr/local/sbin/pktvisord"
      config_file: "/home/gpazuch/Projects/ns1labs/orb-agent.yaml"

  cloud:
    api:
      address: https://localhost
    mqtt:
      address: tls://localhost:8883
      id: ""
      key: ""
      channel_id: ""
```
