### ISSUE TITLE
Running orb agents through configuration files does not provide taps options, so policies could not be created

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#947]
![policy_file_agent.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/2962b1e7-ab98-4be4-a895-f237cc99b84f)

Steps to reproduce:

- Make sure that your machine has no agent running 
- Provision an agent through configuration file (check the example below)
- Try to create a policy

Expected results:

- Policy creation must be enabled using taps from the configuration file

Current result:
- UI notifies that no tap was provided
 

-------------------------------------------------------------
JSON OF AGENT CREATED  THROUGH CONFIG FILE:
```

{
    "id": "a21a7cbf-6348-48e7-9f0e-edd988737d57",
    "name": "my-file-agent",
    "state": "online",
    "channel_id": "4f5844ba-792f-42d2-bfaa-a7a66d1ad776",
    "agent_tags": {
        "agent": "tag"
    },
    "orb_tags": {
        "orb": "tag"
    },
    "agent_metadata": {
        "backends": {
            "pktvisor": {
                "data": {
                    "taps": null
                },
                "version": "4.1.0-develop-f98cb04"
            }
        },
        "orb_agent": {
            "version": "0.12.0-develop"
        }
    },
    "last_hb_data": {
        "backend_state": {
            "pktvisor": {
                "state": "running"
            }
        },
        "group_state": {
            "e59fe087-859d-4591-9493-2fa8910983f8": {
                "channel": "e02ddabc-cec6-4d16-aecb-6eec4434633f",
                "name": "group-agent-tag"
            }
        },
        "policy_state": {}
    },
    "ts_created": "2022-03-14T13:32:38.951622Z",
    "ts_last_hb": "2022-03-14T14:03:41.570183Z"
}
```

-------------------------------------------------------------
AGENT FILE:
```
version: "1.0"

# this section is used by pktvisor
# see https://github.com/ns1labs/pktvisor/blob/develop/RFCs/2021-04-16-75-taps.md
visor:
  taps:
    default_pcap:
      input_type: pcap
      config:
        iface: "wlo1"
        host_spec: "192.168.0.54/32,192.168.0.55/32,127.0.0.1/32"

# this section is used orb-agent
# most sections and keys are optional
orb:
#  # these are arbitrary key value pairs used for organization in the control plane and UI
  backends:
    pktvisor:
      binary: "/usr/local/sbin/pktvisord"
  tags:
    agent: tag
  tls:
    verify: true
  cloud:
    config:
      # optionally specify an agent name to use during auto provisioning
      # hostname will be used if it's not specified here
      agent_name: my-file-agent
      auto_provision: true

    api:
      address: https://orb.live
      # if auto provisioning, specify API token here (or pass on the command line)
      token: <token>
    mqtt:
      address: tls://orb.live:8883
#      # if not auto provisioning, specify agent connection details here
#      id: "AGENT_UUID"
#      key: "AGENT_KEY_UUID"
#      channel_id: "AGENT_CHANNEL_UUID"
```

**Comment by manrodrigues** [comment]
INVALID..
MY CONFIG FILE WAS WITHOUT THE PATH TO THE FILE:

 ```
   backends:
      pktvisor:
         binary: "/usr/local/sbin/pktvisord"
         config_file: "/usr/local/orb/agent.yaml"
```
